plugins {
    id 'java'
    id 'war'
}

group = 'w2l.inspired'
version = '1.0'


war{
    archiveBaseName ='simpleDao'
    archiveVersion = ''
    from("/src/main/resources"){

        include ('customers.xml')
        into('WEB-INF');
        include ('context.xml')
        into('WEB-INF');
    }

}




repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'jakarta.servlet', name: 'jakarta.servlet-api', version: '6.0.0'

    implementation group: 'org.springframework', name: 'spring-beans', version: '7.0.4'
    implementation 'org.springframework:spring-webmvc:7.0.4'

    implementation 'org.apache.logging.log4j:log4j-api:2.20.0'
    implementation 'org.apache.logging.log4j:log4j-core:2.20.0'

    testImplementation group: 'jakarta.servlet', name: 'jakarta.servlet-api', version: '6.0.0'

    // Импортируем BOM для управления версиями всей платформы JUnit
    testImplementation platform('org.junit:junit-bom:6.0.2')
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    // Явно добавляем launcher той же версии
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testImplementation group: 'org.mockito', name:'mockito-core',version: '5.3.1'
    testImplementation("org.springframework:spring-test:7.0.4")
    testImplementation 'org.hamcrest:hamcrest:2.2'

    //https://mvnrepository.com/artifact/org.glassfish.web/jakarta.servlet.jsp.jstl
    implementation 'org.glassfish.web:jakarta.servlet.jsp.jstl:3.0.1'
   // https://mvnrepository.com/artifact/jakarta.servlet.jsp.jstl/jakarta.servlet.jsp.jstl-api
    implementation 'jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:3.0.0'
    //https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-thymeleaf
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf:3.1.1'

}

test {
    useJUnitPlatform()
}// https://mvnrepository.com/artifact/org.springframework/spring-beans
